import assets from "../../../assets";

const Footer = () => {
  return (
    <div className="landing-footer-desktop">
      <a
        href="https://s3.ap-south-1.amazonaws.com/cdn.mac1j.com/apks/UNICONBET-LATEST.apk"
        target="_blank"
      >
        <div className="landing-footer-desktop__number">
          <div className="android-button"></div>
        </div>{" "}
      </a>
      <a
        href="https://s3.ap-south-1.amazonaws.com/cdn.mac1j.com/apks/UNICON365SCORE.apk"
        target="_blank"
      >
        <div className="landing-footer-desktop__number">
          <div className="android-button-2"></div>
        </div>{" "}
      </a>
      <a href="https://wa.link/unicon365">
        <div className="landing-footer-desktop__number">
          <div className="landing-footer-social-button whatsapp"></div>
          <div>WHATSAPP NOW!</div>
        </div>
      </a>
      <div className="landing-footer-desktop__companies-wrapper">
        <div className="landing-footer-desktop__companies">
          <div className="landing-footer-desktop__companies-img">
            <a>
              <img
                loading="lazy"
                src={assets.gaming1}
                alt="gaming"
              />
            </a>
          </div>
          <p className="landing-footer-desktop__companies-info">
            Unicon365 is a limited liability company incorporated under the laws
            of Curacao Players are requested not to contact any untrusted
            sources for Unicon365 accounts as this is an online site and they
            can only register independently without any agents. Only deposit
            through the account details generated by the system or provided by
            our official support team.
          </p>
        </div>
        <div className="landing-footer-desktop__companies-logos-rows-wrapper">
          <div className="landing-footer-desktop__companies-logos-row">
            <img
              loading="lazy"
              src={assets.upi}
              alt="gaming"
            />
            <img
              loading="lazy"
              src={assets.bankTransfer}
              alt="gaming"
            />
            <img
              loading="lazy"
              src={assets.BeGamble}
              alt="gaming"
            />
            <img
              loading="lazy"
              src={assets.gamblingCom}
              alt="gaming"
            />
            <img
              loading="lazy"
              src={assets.corga2}
              alt="gaming"
            />
            <img
              loading="lazy"
              src={assets.mga}
              alt="gaming"
            />
          </div>
        </div>
      </div>
      <div className="landing-footer-desktop__social-wrapper">
        <div className="landing-footer-social">
          <a
            href="https://instagram.com/_u/unicon_365"
            target="_blank"
            className="landing-footer-social-button instagram"
          >
            <span>unicon_365</span>
          </a>
          <a
            href="https://telegram.me/+UY__3D7R0WdhNzg0"
            target="_blank"
            className="landing-footer-social-button telegram"
          >
            <span>+UY__3D7R0WdhNzg0</span>
          </a>
        </div>
        <div className="landing-footer-desktop__social-copyright">
          <span className="rulesAndRegulations">
            <span>Rules</span>
            <span className="andSymbol"> </span>
            <span>Regulations</span>
          </span>
          <span className="copyright"> </span>
          <span> 2016-2022 </span>
          <span style={{marginLeft:'7px'}}>v. 2.51</span>
        </div>
      </div>
      <div className="landing-footer-desktop__companies-wrapper privacyPolicy">
        <span className="spanPolicy">Privacy Policy</span>
        <span>|</span>
        <span className="spanPolicy">Terms and Conditions</span>
      </div>
      <div className="landing-footer-desktop__companies-wrapper responsibleGaming">
        This game may be habit forming or financially risky. Play responsibly.
      </div>
    </div>
  );
};

export default Footer;
